const nextJest = require('next/jest');

const createJestConfig = nextJest({
  dir: './',
});

/** @type {import('jest').Config} */
const config = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 30,
      functions: 20,
      lines: 60,
      statements: 60,
    },
  },
  testPathIgnorePatterns: [
    '/node_modules/',
    '/.next/',
    '/test/',
    '/e2e/',
    '\\.?vitest\\.',
    // Excluded tests that use incompatible APIs or have environment issues
    'src/app/api/extract-receipt/pdf-ocr.test.ts',
    'src/app/api/classify-receipt/classify-receipt.test.ts',
    'src/lib/pdf-to-image-multipage.test.ts',
    'src/lib/pdf-to-image.test.ts',
    'src/app/api/convert-pdf/convert-pdf.test.ts',
    'src/app/api/generate-pdf/generate-pdf.test.ts',
    'src/middleware.test.ts',
    'src/app/api/generate-pdf/integration.test.ts',
    'src/app/api/extract-receipt/extract-receipt.test.ts',
    'src/app/api/generate-pdf/pdf-attachment.test.ts',
    'src/app/api/generate-pdf/attachment-render.test.ts',
    'src/app/api/generate-pdf/multipage-pdf.test.ts',
    'src/app/api/documents/upload/__tests__/route.test.ts',
    'src/app/api/documents/list/__tests__/route.test.ts',
    'src/app/api/auth/magic-link/verify/route.test.ts',
    'src/app/api/auth/register/send-verification/route.test.ts',
    'src/app/api/auth/magic-link/send/route.test.ts',
    'src/app/api/auth/passwort-vergessen/route.test.ts',
    'src/app/api/auth/verify-email/route.test.ts',
    'src/lib/zugferd-service.test.ts',
    'src/lib/rate-limit.test.ts',
    'src/lib/image-processor.test.ts',
    'src/lib/__tests__/docbits-auth-password.test.ts',
    'src/lib/FormDataAccumulator.test.ts',
    'src/__tests__/integration/auth-login.integration.test.ts',
    'src/app/api/extract-receipt/kreditkartenbeleg.test.ts',
    'src/app/api/generate-pdf/route.test.ts',
    'src/app/api/generate-pdf/eigenbeleg-fix.test.ts',
    'src/lib/__tests__/embeddings.test.ts',
    'src/lib/__tests__/opensearch.test.ts',
    'src/lib/env.test.ts',
    'src/lib/docbits-auth.test.ts',
    'src/__tests__/integration/auth-real-user.integration.test.ts',
    'src/__tests__/routes-validation.test.ts',
    'src/components/ImageEditor.test.tsx',
    'src/components/ImageEditor.pdf.test.tsx',
    'src/components/ImageEditor.integration.test.tsx',
    'src/app/release-notes/page.test.tsx',
    'src/app/components/MultiFileDropzone.test.tsx',
    'src/app/bewirtungsbeleg/page.test.tsx',
    'src/app/components/BewirtungsbelegForm.test.tsx',
    'src/app/components/BewirtungsbelegForm.error.test.tsx',
    // Additional Vitest-specific tests
    'src/app/api/auth/__tests__/nextauth-config.test.ts',
    'src/lib/email/__tests__/token-storage-redis.test.ts',
    'src/app/api/auth/forgot-password/route.test.ts',
    'src/lib/email/templates/verification.test.ts',
    'src/app/api/auth/__tests__/auth-flows.e2e.test.ts',
    'src/app/api/auth/setup-password/route.test.ts',
    'src/lib/email/templates/templates.test.ts',
    'src/app/auth/registrieren/page.test.tsx',
    'src/app/auth/passwort-vergessen/page.test.tsx',
    'src/app/meine-belege/__tests__/page.test.tsx',
    'src/app/components/__tests__/BewirtungsbelegForm.test.tsx',
    'src/app/api/auth/reset-password/route.test.ts',
    'src/app/auth/passwort-einrichten/page.test.tsx',
    'src/lib/email/utils.test.ts',
    'src/lib/email/token-storage.test.ts',
    'src/app/auth/anmelden/page.test.tsx',
    'src/lib/email/mailer.test.ts',
    'src/app/api/extract-receipt/route.test.ts',
    'src/middleware/__tests__/ensure-user-index.test.ts',
    'src/lib/__tests__/spaces.test.ts',
    'src/lib/__tests__/opensearch-schema.test.ts',
    'src/lib/__tests__/FormDataAccumulator.test.ts',
    'src/__tests__/utils/mock-spaces.ts',
    'src/lib/__tests__/OcrExtractionIntegration.test.ts',
    'src/__tests__/fixtures/sample-documents.ts',
    'src/__tests__/fixtures/sample-embeddings.ts',
    'src/__tests__/fixtures/sample-receipt-metadata.ts',
    'src/__tests__/magic-link-e2e.test.ts',
    'src/__tests__/utils/mock-session.ts',
    'src/__tests__/utils/mock-opensearch.ts',
    'src/__tests__/magic-link-integration.test.ts',
    'src/app/components/BewirtungsbelegForm.unit.test.tsx',
    'src/app/page.test.tsx',
    'src/components/Header.test.tsx',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  testMatch: [
    '**/__tests__/**/*.[jt]s?(x)',
    '**/?(*.)+(test).[jt]s?(x)',
  ],
  testEnvironmentOptions: {
    customExportConditions: ['node', 'node-addons'],
  },
};

module.exports = createJestConfig(config); 
