# DigitalOcean App Platform Configuration
name: bewirtungsbeleg-app
services:
- name: web
  source_dir: /
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXTAUTH_URL
    value: ${APP_URL}
  - key: NEXTAUTH_SECRET
    value: ${NEXTAUTH_SECRET}
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
